### ISSUE TITLE
Question - What happens when multiple pools are created?

### ISSUE THREAD

**Issue by lucaciraolo** [josdejong/workerpool#112]
Apologies if this is a dumb question but what happens if I create multiple pools and execute tasks to them. Do they both compete for CPU? Or do they alternate tasks?

Thansk

**Comment by josdejong** [comment]
Hi, it's perfectly fine to ask any question :+1:  :smile: 

Suppose my computer has 4 CPU's, and I create 2 workerpools each with 4 workers, and I put all of them to work, then they will compete for CPU, and this is handled by the operating system. 

The same is the case when you create 1 workerpool with 8 workers whilst having 4 CPU's: they will simply compete for CPU and run in parallel, handled by your operating system. And when creating 16 workers, each 4 of them will share a single CPU. They progress in parallel and will finish at the same time, but it will take 4x as long since they have only 1/4th of the CPU time for themselves.
