### ISSUE TITLE
question: task execution order, possible to share variables?

### ISSUE THREAD

**Issue by lab4quant** [josdejong/workerpool#149]
Hello, If I need `tasks` send to `workerpool` to be executed in order, could this be done?
Also, is it possible to have all spawned works to share a "global" context?

example: your other interesting project http://mathnotepad.com/

let's say I have 100 cells of code to feed to `workerpool`, and I need to them to be executed in the same order as notepad app, also cells share variables.

if yes, an example would be great!

thank you!

**Comment by josdejong** [comment]
> Hello, If I need tasks send to workerpool to be executed in order, could this be done?

Yes, you can for example use `Promise.all` to start multiple tasks in parallel, and when all tasks are resolved, you get back the results in an array where the order of the results corresponds with the order of the original tasks.

> Also, is it possible to have all spawned works to share a "global" context?

Do you mean sharing an initial state as discussed in #65?

**Comment by lab4quant** [comment]
@josdejong , thanks for the update, as far as I know, `Promise.all()` run promises in parallel, execution order is not guaranteed.

I'm talking about scenario like your `mathnotebook` app, say I create a variable in cell#1, then in cell#2 I updated the variable created from cell#1, in this case, cell#1 must run before cell#2

Actually I'm working on a similar notebook-like app, I want to execute cells of code, in non-blocking way, as some cell of code might take long time

**Comment by josdejong** [comment]
If you need to execute tasks _in order_ that basically means you want to execute them in series instead of in parallel, right? The part that `workerpool` can do for you is execute tasks in parallel, where the order of execution is not defined. If your tasks do have dependencies on each other, you will need to model and resolve these dependencies yourself, and pass results of say cell#1 when starting the calculation for cell#2. Suppose cell#2 and cell#3 are both depending on only cell#1 and not on each other, then you could first calculate cell#1, and after that, calculate cell#2 and cell#3 in parallel.

**Comment by lab4quant** [comment]
@josdejong thanks for the clearification, i guess i'll have to create my own serial logic
