### ISSUE TITLE
Question: Task Queue Implementation

### ISSUE THREAD

**Issue by enioluwa23** [josdejong/workerpool#164]
In considering this package for a high-performance project, I decided to look into how the task queue is implemented in [Pool](https://github.com/josdejong/workerpool/blob/master/src/Pool.js). I noticed a simple array implementation is used, with `Array.shift` used to dequeue tasks. This requires adjusting the index for every other element in the array, and thus if there are more than a couple of tasks queued, dequeuing can be pretty slow. There are more performant implementations, but first I wanted to ask, is there a reason for this specific implementation?

**Comment by josdejong** [comment]
If you're interested, you could create a real-world (!) benchmark to see where the bottlenecks in the library are. I'm sure there is room for improving the performance, but first we should identify places in the code where improvements are possible and will actually have an impact on the performance.

I expect the duration of the `Array.shift` operation to be neglectable when measured in a real-world application (compared to say creating a task object and sending the object to the worker and receiving the result etc). If it turns out to be a bottleneck we can see if we can come up with more performant solutions.

**Comment by enioluwa23** [comment]
I am more used to working in languages that have native queue objects, intended to make the performance of both enqueuing and dequeuing independent of how many objects are already in the queue. So the use of `Array.shift` caught my eye on the first pass through. If you feel the impact on performance is negligible, that's fine. If I end up using this library, I will try and do a deep dive help out with benchmarks. For now, I will close this issue but if you want help from the general community with those you could open a new issue specifically about benchmarks.

**Comment by josdejong** [comment]
👍 

Again, I expect the performance difference compared to using some queue is neglectable in real-world cases of workerpool, but feel welcome prove me wrong 😉.

**Comment by enioluwa23** [comment]
Again, if you need help with benchmarking, open a new issue 🙂
