### ISSUE TITLE
Promise timeout starts too early

### ISSUE THREAD

**Issue by eclipsesk** [josdejong/workerpool#25]
If there are more jobs than minWorkers, these are queued as expected. The problem is that the timeout's timer starts as soon as they are pushed into the queue. It would be great if the timer would start when the job is really started that is when is popped out the queue and forked.
One solution could be to pass the timeout  value directly in the exec function of pool, then store the timeout value in the promise object and then in _next() start the timer. I've tested this solution and it works

**Comment by josdejong** [comment]
Thanks, that makes a lot of sense indeed.

If anyone is interested in working a solution out for this issue just let me know.

**Comment by eclipsesk** [comment]
I can do it, but I can't mantain the same structure as pool.exec( fn ).timeout( delay ).

**Comment by josdejong** [comment]
Thanks @eclipsesk , that would be great! I think you're right and that we have to change the API, else we would have to interleave the logic of both worker and Promise too much to pull this off. 

I like your proposal of `pool.exec(fn, [timeout])`, and it may be even nicer to change it to `pool.exec(fn, { timeout: number})` so we can extend `exec` with more options in the future if needed.

To make this a smooth change, I think we'll have to keep the current `.timeout(delay)` working, and output a deprecation warning when it's used. Then in a next breaking version we can remove the deprecated function.

**Comment by eclipsesk** [comment]
great, I sent a pull request with the required fix. However it's my first pull request so if it is incorrect you can use it to commit on the main branch.

**Comment by josdejong** [comment]
thanks! How do you think about introducing an options object `{timeout: number}`?

and can you add a deprecation warning when the old `.timeout()` is used? (`console.warn(...)`)

If you push additional commits to your current branch the PR will automatically update.

**Comment by eclipsesk** [comment]
I think it is overkill to introduce an options object for one option. But yes I can do these changes, let me just know what you would to do...

**Comment by josdejong** [comment]
ha ha, yes that's true, it's a bit overkill for just one option. 

I really prefer an object `{timeout: number}` though. The API is extensible for the future, the code where you use `exec` becomes more readable since you see a named parameter, and there is a more clear distinction between the first two arguments (function name and parameters), and the third one (options).

**Comment by eclipsesk** [comment]
perfect, I will do it asap

**Comment by eclipsesk** [comment]
First fix done. For the second one, I can't call console.warn because I still use that function to set the timer.

**Comment by josdejong** [comment]
Thanks, I will review your PR coming Friday (I hope), and do some testing to see whether it indeed works as it should.

**Comment by josdejong** [comment]
Thanks! I will merge your PR now and will do a little bit of refactoring afterwards.

**Comment by josdejong** [comment]
@eclipsesk I was thinking whether it wouldn't be possible to keep using the existing `.timeout()` and delay the start of the actual timer until the task is started. Turned out to be quite easy, see this PR: https://github.com/josdejong/workerpool/pull/27

What do you think, shall we go with that solution?

**Comment by eclipsesk** [comment]
yeah, it seems correct to me... if there aren't unwanted effects your solution doesn't break the API

**Comment by josdejong** [comment]
I had expected getting this to work within the current API would be complicated but it turned out to be quite simple! There are indeed no unwanted effects as far as I can see, and we can keep the existing API which is a big plus. Ok will merge this solution and publish the next release then. Thanks!
