### ISSUE TITLE
inner method calls not working 

### ISSUE THREAD

**Issue by MariusAlch** [josdejong/workerpool#28]
```
const workerpool = require('workerpool');
const pool = workerpool.pool();

const job = (n: number): number => {
  return returnsInput(n);
}

function returnsInput (n: number) {
  return n
}

pool.exec(job, [10])
  .then((res: number) => {
    console.log('im done');
    pool.clear();
  });
```

promise does not get resolved (probably) so I dont get the output "im done"

if I replace `return returnsInput(n);` with any value instead of function call for example `n` method gets resolved.

**Comment by josdejong** [comment]
That's correct, functions passed from the main process to a child process cannot contain references to externally defined functions or variables since the function is serialized and send to the worker, see docs:

https://github.com/josdejong/workerpool/#offload-functions-dynamically

If you need to reference functions or variables, you will have to create a separate worker file ([see docs](https://github.com/josdejong/workerpool/#dedicated-workers)).

To figure out whether something goes wrong (and what), you can catch errors from the promise:
```js
pool.exec(job, [10])
  .then((res: number) => {
    console.log('im done');
    pool.clear();
  })
  .catch(function (err) {
    console.error(err);
  });
```
in your example it will throw an error like "returnsInput is undefined".

I think I should add a `.catch()` to all examples, since it's best to always catch errors from promises.

**Comment by josdejong** [comment]
I've added `.catch(...)` to all examples now in v2.2.3
