### ISSUE TITLE
Using wokerpool on multi node.js processes running on the same server

### ISSUE THREAD

**Issue by basheer-shahrour** [josdejong/workerpool#355]
I have a server with 6 CPU logical cores, there is 6 node.js (v16) processes running express.js app within the server and managed by pm2 process manager, and I'm using Nginx proxy to load balance the traffic between the processes.

Nginx configuration:

upstream nodes {
   ip_hash;
   server localhost:3001;
   server localhost:3002;
   server localhost:3003;
   server localhost:3004;
   server localhost:3005;
   server localhost:3006;
}
server {
  server_name SERVER_IP_ADDRESS;
       location / {
        proxy_pass          http://nodes;
    }
}
     location / {
        proxy_pass          http://nodes;
    }
}

I have a CPU intensive task in one of my endpoints and I want to offload it on a worker thread using workerpool package, it'll create worker threads corresponds to the number of CPU cores, so 6 thread for each node.js process, which mean 36 threads in total.

Is it good to have 36 node.js worker threads on 6 CPU cores? will CPU scheduling time affect app performance?

**Comment by josdejong** [comment]
You _roughly_ have the following: say you have 36 tasks that take 10 seconds each. 

- If you execute them in 1 process, it will take roughly 360 seconds. The first task returns after 10 sec, the last after in 360 sec.
- If you execute them in 6 processes, it will take roughly 60 seconds. The first task returns after 10 sec, the last after in 60 sec.
- If you execute them in 36 processes, it will take roughly 60 seconds. All tasks return after 60 seconds. Each task is 6 times slower than it could have been, because it is sharing the same CPU core with 5 other tasks simultaneously. This _can_ be interesting if you have a mix of long and short tasks: if there are enough processes available, short tasks will not be blocked in a queue when some large task is running.

There is one important caveat here: if you spin up more processes, you'll have to make sure that you have enough memory for all of them.
