### ISSUE TITLE
Type of error is not kept when error goes from inside to outside the workerpool

### ISSUE THREAD

**Issue by slimee** [josdejong/workerpool#363]
Figure an error of "type" CalculationError 
```
class CalculationError extends Error{};
```

And it's loaded and thrown from inside the workerpool:

```
throw new CalculationError();
```

The error propagates from inside the workerpool context to the caller context.

The statement `error instanceof CalculationError` is:
- true inside the workerpool (and that's OK)
- false inside the caller context (and that's KO for me)

Do you notice this behavior?
How should I preserve the type of errors thrown through the workerpool context?
Regards

**Comment by josdejong** [comment]
The data transferred between the main process and a worker must be plain JSON. Any class instance information is lost. If you want to transfer a `class` instance, you'll need to put a serialization and deserialization logic of your own in place. If you want to transfer an error class, maybe you can let your function return an object `{ success, error }` instead of throwing an exception, in combination with logic to turn your data and error message into plain JSON.
