### ISSUE TITLE
executeAll API request

### ISSUE THREAD

**Issue by kvandelden** [josdejong/workerpool#55]
Is there a way to execute a method on all workers?   We are trying to invalidate cached data the workers could have cached.. but we can't call an API that guarantees it will run on each worker.  Any help would be greatly appreciated.

Thanks,
Kurt

**Comment by josdejong** [comment]
There is no API to send some request to each of the workers. 

A simply (but probably inefficient)  way is to throw away your pool and simply create a new pool with fresh workers.

A hacky solution that _may_ work is to loop over all `pool.workers` and on each, call `worker.exec(method, params, resolver)`. Since this is internal, it may change in future versions and break if your behavior depends on it.

**Comment by kvandelden** [comment]
What do you think about the possibility of an addition task queue on each worker.  If a worker has it's own task queue,  one possible policy is to have it process it's own task queue before being available to process items on the round robin task queue.  The execAll api would simply post a tasks to each workers task queue.. and possibly complete without waiting.

**Comment by josdejong** [comment]
I have to give that some more thought. I'm not sure whether this is an edge case or something generic that is useful in many cases We should not blindly add lots of features ending with a complicated, bloated library. 

I don't have a clear idea on the impact of implementing such an `pool.execAll` method, it may turn out to be quite easy if we can internally simply call `worker.exec(method, params, resolver)` on each of the workers directly as the first next task (ignoring the queue). Since it's bypassing the queue and executes on all workers, it may be a good idea to name the method clearly different, maybe something like `pool.broadcast`. Do you have any ideas on how to work this out in a generic way?

**Comment by kvandelden** [comment]
We have gone with a Websockets solution for our cache invalidation challenge.  I still believe an executeAll / broadcast like API would be helpful to developers dealing with worker pools.

Thanks for maintaining a great npm-package..

**Comment by josdejong** [comment]
Thanks for your feedback Kurt! Good to hear you have a solution. 

Since I'm not sure how generic this feature is and if it will be broadly used, I will close this issue now. Please re-open in the future if more use cases pop up.
