### ISSUE TITLE
Support asynchronous initialization

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [josdejong/workerpool#9]
If a worker uses a dynamic module loader it cannot be used with workerpool directly because the worker might not have registered it's **onmessage** handler at the time WorkerHandler sends the exec call.

I have implemented support for asynchronous initialization [here](https://github.com/natlibfi-arlehiko/workerpool/commit/2d5c3385a2e3da4627c8060a92738d74590956c6). If you want this change I can prepare a proper pull request with updated documentation as well.

Thank You.

**Comment by josdejong** [comment]
That's certainly interesting, thanks for the suggestion. 

I've had a short look in your implementation. If I see it correctly it works by specifying `handler.enableAsyncInit();` on the side of the Pool. I think it would be great if this would be handled purely on the Worker side instead, so that on the side of the Pool you don't need to know any implementation details of the worker (except for it's public API). Here some ideas:

- When a message is sent to the Worker whilst `workerpool.worker(methods)` hasn't been called yet. In that case, the Worker could queue all messages until the methods have been registered and after that flush them. This requires that you're only allowed to call `workerpool.worker(methods)` once.
- Allow the methods registered with the worker via `workerpool.worker(methods)` to return a Promise instead of a function. In case of a Promise, calls to this method are queued until the Promise resolves.
- Create an explicit method `workerpool.asyncWorker(asyncMethods: Promise)`.

What do you think, would something like that work or am I overlooking something?

**Comment by natlibfi-arlehiko** [comment]
The problem here is that `workerpool.worker` is not the first call if you are loading modules asynchronously. That's why the implementation is done in the Pool/WorkerHandler side.

**Comment by josdejong** [comment]
Yes, so the `workerpool.worker` should go *inside* the callback of the asynchronous loading, something like:

```js
System.import('some_module')
    .then(some_module => {
      workerpool.worker({ some_module })
    })
    .catch(error => {
        //...
    });
```

This could only work when workerpool is already listening for messages even before `workerpool.worker` is called.

**Comment by natlibfi-arlehiko** [comment]
Hmm, yeah. This is why WorkerHandler pushes the exec calls to *initCallbacks* array, because the worker might not yet have called `workerpool.worker`. When that method is called those stored callbacks are dispatched.

Actual the name *initCallbacks* is misleading and should be changed to something else.

**Comment by natlibfi-arlehiko** [comment]
Just to summarize: I don't see a way to implement this purely in the worker side without using custom logic before calling module loader:

```js
onmessage = function(msg) {
  //Store the message
};

require(['workerpool/dist/workerpool'], function(workerpool) {
  //Call workerpool.worker and handle buffered messages somehow
});
```

But I don't think it's reasonable to implement that in every worker script instead of having the logic in workerpool itself.

**Comment by josdejong** [comment]
I'm not sure either if it's doable. Let me give it some more thought coming weekend. It would be so neat if this could be handled purely on the worker's side.

**Comment by josdejong** [comment]
I have an idea. What we could do is introduce a message `loaded` which is sent from the worker to the workerpool once when the worker is ready. This message may be sent synchronously or asynchronously: that doesn't matter. The workerpool queues all messages until this `loaded` message is received from the worker, signalling that the worker is ready. That will require no new public API at all (not in the workerpool and not in the worker), we only have to change some internal things in the communication flow between workerpool and worker.

**Comment by natlibfi-arlehiko** [comment]
Ok, I can look into it.

**Comment by josdejong** [comment]
Thanks! Thinking about it: maybe `ready` would be a better name for this internal event instead of `loaded`.

**Comment by natlibfi-arlehiko** [comment]
The new implemenation is available [here](https://github.com/natlibfi-arlehiko/workerpool/tree/worker-ready).

The changes described in #11 are also pulled in.

**Comment by natlibfi-arlehiko** [comment]
PR: #15

**Comment by natlibfi-arlehiko** [comment]
#16
